version: '3.4'

services:

  friends-user-service:
    image: friends-user-service:latest
    environment:
      PORT: 8000
      KARTOFFEL_URL: http://outgoing-proxy-service:8000/kartoffel
      ELASTIC_APM_ACTIVE: 'true'
      ELASTIC_APM_SERVER_URL: http://apm:8200
    ports:
      - 8000:8000
  
  redis:
    image: redis
    ports:
      - 6379:6379

  outgoing-proxy-service:
    image: spike-proxy-service-master
    environment:
      MODE: outgoing
      PORT: 8000
      SPIKE_REDIS_HOST: redis://redis
      SPIKE_CLIENT_ID: hvOItpV~jv0ZiIqEAxLrYx8sxvDHmPfNiw9wtOSz
      SPIKE_CLIENT_SECRET: e2ar_pCJc27RdT4dFw~6ONYJ~5gVgsWfh9cjuUJ0YyVL0simY3VwehAYwe0qPB_uUIjRXFKzHJUqW7A_KM1DBpPYtQQ183JcdLFr
      SPIKE_URL: https://51.144.178.121:1337/oauth2/token
      TOKEN_GRANT_TYPE: client_credentials
      SPIKE_USER_SERVICE_REDIS_KEY_NAME: kartoffel
      SPIKE_PUBLIC_KEY_FULL_PATH: ./certificate/publicKey.pem
      USE_REDIS: 'true'
      OUTGOING_SERVICES: '[{"route":"/kartoffel/*","pathRewrite":{"^/kartoffel":""},"target":"${KARTOFFEL_URL}","audience":"kartoffel"}]'
    ports:
      - 8001:8000

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.0"
    environment:
      - discovery.type=single-node
    container_name: elasticsearch
    ports:
      - "9200:9200"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:9200"
      interval: 5s
      timeout: 10s
      retries: 5

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.5.0"
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  apm:
    image: "docker.elastic.co/apm/apm-server:7.5.0"
    container_name: apm
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch